homeassistant:
  name: Home
  latitude: 39.329149
  longitude: -84.249620
  elevation: 223
  unit_system: imperial
  time_zone: America/New_York
  # external_url: "https://www.example.com"
  internal_url: "http://homeassistant.local:8123"
  # allowlist_external_dirs:
  #   - /usr/var/dumping-ground
  #   - /tmp
  # allowlist_external_urls:
  #   - "http://images.com/image1.png"
  # media_dirs:
  #   media: /media
  #   recordings: /mnt/recordings
  # legacy_templates: false